#!/bin/sh
super + {Return}
        $TERMINAL

# program launcher
super + shift + d
        run_dmenu

# media keys
XF86Audio{Next,Prev,Play,Stop}
    mpc {next,prev,toggle,stop}

# volume
XF86AudioRaiseVolume
	pactl set-sink-volume 0 +5%

XF86AudioLowerVolume
    pactl set-sink-volume 0 -5%

XF86AudioMute
    pactl set-sink-mute 0 toggle

# screenshot keybindings
ctrl + alt + a
    flameshot gui
# translate with screenshot
ctrl + alt + w
	flameshot gui && xclip -o -sel clip -t image/png > /tmp/test.png && translator "$(tesseract /tmp/test.png stdout)"

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# dunst
super + shift + x
	dunstctl close

# gaps
# translate select text
alt + w
# super + ctrl + Tab
	translator "`xclip -o`"
